name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  test:
    runs-on: namespace-profile-large
    if: |
      contains(github.event.head_commit.message, 'skip ci') == false &&
      needs.optimize_ci.outputs.skip == 'false' &&
      !startsWith(github.event.pull_request.title, 'docs:') &&
      !startsWith(github.event.pull_request.title, 'style:')
    env:
      CI: true
    permissions:
          contents: read
          id-token: write
    steps:
      - uses: namespacelabs/nscloud-checkout-action@v8
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
      - name: bootstrap
        with:
          node-version: 20.x

      - name: lint
        run: npx nx run @apps/LmsPortal:lint

      - name: format
        run: npx nx format:write

      - name: build
        run: npx nx run-many -t lint test build typecheck
